package web

import (
	"encoding/json"
	"io/fs"
	"strings"
	"testing"
)

// manifest mirrors only the fields these tests have an opinion about.
type manifest struct {
	StartURL string `json:"start_url"`
	Scope    string `json:"scope"`
	Display  string `json:"display"`
	Icons    []struct {
		Src     string `json:"src"`
		Sizes   string `json:"sizes"`
		Type    string `json:"type"`
		Purpose string `json:"purpose"`
	} `json:"icons"`
}

func readManifest(t *testing.T) (manifest, string) {
	t.Helper()
	raw, err := fs.ReadFile(FS(), "manifest.webmanifest")
	if err != nil {
		t.Fatalf("manifest is not embedded: %v", err)
	}
	var m manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("manifest is not valid JSON: %v", err)
	}
	return m, string(raw)
}

// The manifest is JSON, so it cannot carry the comment explaining why
// start_url is what it is. This is that comment, in a form that fails.
//
// start_url must stay "/". resolveSession() in app.js reads the room and its
// key back out of localStorage when it lands there, so a launcher never needs
// either one in the URL. Both ways of putting a room in start_url break E2EE:
// a per-room manifest is generated by the server, which hands it the key that
// the URL fragment exists to keep away from it; and a client-built data: URL
// manifest is refused by the CSP, whose manifest-src falls back to
// default-src 'self'.
func TestManifestStartsAtTheRootAndCarriesNoRoomOrKey(t *testing.T) {
	m, raw := readManifest(t)

	if m.StartURL != "/" {
		t.Errorf("start_url = %q, want %q -- read the comment above this test", m.StartURL, "/")
	}
	if m.Scope != "/" {
		t.Errorf("scope = %q, want %q", m.Scope, "/")
	}

	// The invariant underneath: nothing room- or key-shaped anywhere in the
	// file. Checking the text rather than the parsed fields catches a room
	// smuggled into some field this struct does not model.
	for _, bad := range []string{"/r/", "#k", "k="} {
		if strings.Contains(raw, bad) {
			t.Errorf("manifest contains %q; it must never carry a room or a key", bad)
		}
	}
}

// A declared icon that is not embedded is a 404, and a 404 on an icon makes
// the install prompt quietly not appear rather than fail.
func TestManifestIconsAreEmbedded(t *testing.T) {
	m, _ := readManifest(t)
	if len(m.Icons) == 0 {
		t.Fatal("no icons declared")
	}
	for _, ic := range m.Icons {
		name := strings.TrimPrefix(ic.Src, "/")
		if _, err := fs.Stat(FS(), name); err != nil {
			t.Errorf("icon %q is declared but not embedded: %v", ic.Src, err)
		}
	}
}

// 192 and 512 are what installers look for. The maskable copy is separate
// because Android crops icons to its own shape, and cropping artwork that is
// already rounded eats the corners.
func TestManifestDeclaresTheSizesInstallersWant(t *testing.T) {
	m, _ := readManifest(t)

	var has192, hasAny512, hasMaskable bool
	for _, ic := range m.Icons {
		if ic.Purpose == "maskable" {
			hasMaskable = true
			continue
		}
		switch ic.Sizes {
		case "192x192":
			has192 = true
		case "512x512":
			hasAny512 = true
		}
	}
	if !has192 {
		t.Error("no 192x192 icon with purpose any")
	}
	if !hasAny512 {
		t.Error("no 512x512 icon with purpose any")
	}
	if !hasMaskable {
		t.Error("no maskable icon; Android will crop the rounded corners off")
	}
	if m.Display != "standalone" {
		t.Errorf("display = %q, want standalone", m.Display)
	}
}

// The manifest does nothing unless the document links it, and iOS ignores
// manifest icons for the home screen in favour of apple-touch-icon -- without
// one it screenshots the page instead.
func TestIndexLinksTheManifestAndTheIcons(t *testing.T) {
	raw, err := fs.ReadFile(FS(), "index.html")
	if err != nil {
		t.Fatalf("index.html is not embedded: %v", err)
	}
	for _, want := range []string{
		`rel="manifest" href="/manifest.webmanifest"`,
		`rel="apple-touch-icon" href="/icons/apple-touch-icon.png"`,
		`rel="icon" href="/icons/icon.svg"`,
	} {
		if !strings.Contains(string(raw), want) {
			t.Errorf("index.html is missing %s", want)
		}
	}
	for _, name := range []string{"icons/apple-touch-icon.png", "icons/icon.svg"} {
		if _, err := fs.Stat(FS(), name); err != nil {
			t.Errorf("%s is linked but not embedded: %v", name, err)
		}
	}
}
